baseurl = "/"
languageCode = "en-us"
theme = "hugo-theme-terminal"
paginate = 5
highlightjsLang = ["r", "yaml"]
highlightjsTheme = "github"

[params]
  contentTypeName = "post"
  themeColor = "red"
  showMenuItems = 2
  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
  highlightjsLang = ["r", "yaml"]
  highlightjsTheme = "github"

[languages]
  [languages.en]
    title = "J-Stone"
    subtitle = "rstats mostly"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "J-Stone"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"
